apiVersion: apps/v1
kind: Deployment # Kubernetes resource kind we are creating
metadata:
  name: spring-boot-k8s
spec:
  selector:
    matchLabels:
      app: spring-boot-k8s
  replicas: 2 # Number of replicas that will be created for this deployment
  template:
    metadata:
      labels:
        app: spring-boot-k8s
    spec:
      containers:
        - name: spring-boot-k8s
          image: arjundevops92/test-repo:v4 # Image that will be used to containers in the cluster
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080 # The port that the container is running on in the cluster
---

apiVersion: v1
kind: Service
metadata:
  name: jb-hello-world-service
spec:
  selector:
    app: spring-boot-k8s  # Matches the label of the pod
  ports:
    - protocol: TCP
      port: 8080         # Expose this port on the load balancer
      targetPort: 8080  # Port the application listens on inside the container
  type: LoadBalancer    # Creates an external load balancer
